# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c053b1dce5b35a00193afa790c21c36c"
name = "meowmail-demo-app"
application_url = "https://straight-creative-dj-cases.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "meowmailappdemo.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://straight-creative-dj-cases.trycloudflare.com/auth/callback",
  "https://straight-creative-dj-cases.trycloudflare.com/auth/shopify/callback",
  "https://straight-creative-dj-cases.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
